### PR TITLE
(packaging) Prepare for 3.8.0 release

### PR DESCRIPTION
**Pull request by branan**

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
👍

**Comment by Magisus** [comment]
I think there might also be a spot in the POT file that will change. If you have gettext tools installed, you should try compiling this to catch any other needed updates to the POT file.

**Comment by branan** [comment]
@Magisus shouldn't Jenkins be doing that for me? I've been explicitly excluding POT changes from my commits generally

**Comment by geoffnichols** [comment]
Is this the place in the POT file? https://github.com/puppetlabs/facter/blob/3.8.x/locales/FACTER.pot#L9

**Comment by branan** [comment]
@Magisus @geoffnichols updated the POT file for now. Would still like a bit better guidance on when we need to manually make changes to it vs. when we can expect Jenkins to do the right thing

**Comment by geoffnichols** [comment]
👍

**Comment by Magisus** [comment]
@branan it doesn't commit them for C++ right now :/

**Pull request merged**
