### PR TITLE
(FACT-1906) networking.dhcp fact is blank on RedHat 8 beta

### PR DESCRIPTION
**Pull request by denis-susan**
Added the ability to read /var/lib/NetworkManager/internal-*.leases files and extract dhcp information interface and dhcp servers as the networking.dhcp fact.

### CODE REVIEW

**Comment by denis-susan** [comment]
Passing test: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/Adhoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/RMM_COMPONENT_TO_TEST_NAME=facter,SLAVE_LABEL=beaker,TEST_TARGET=redhat8-64a/540/

**Comment by caseywilliams** [comment]
jenkins please test this on redhat8-64a

**Comment by caseywilliams** [comment]
This LGTM, but let's target it at the 3.11.x branch, so that it can make its way into puppet-agent 5.5.x

**Comment by denis-susan** [comment]
@caseywilliams changed the target, can be merged.

**Pull request closed without merging**
