### PR TITLE
(FACT-832) Update ubuntu acceptance test for AIO

### PR DESCRIPTION
**Pull request by kylog**
This passed for precise at my desk.

### CODE REVIEW

**Comment by kylog** [comment]
@haus this should fix the acceptance test failure on ubuntus that we noted.

/cc @justinstoller

**Comment by haus** [comment]
@kylog I don't know the standard terms for these things in beaker-speak. @joshcooper was mentioning something about this in the AIO standup today. I thought this was going to be called privatebindir or something?

**Comment by kylog** [comment]
Yes it will be `privatebindir` once QENG-1946 is resolved. I don't know the timeframe for that, so filed this, and then FACT-833 to update this once there's a beaker release with `privatebindir`.

This temporary solution is also in place in puppet, e.g. https://github.com/puppetlabs/puppet/blob/8eb9557420bd10cfb268c55a62698136338c9b79/acceptance/config/nodes/rhel7.yaml#L14

Yaks all the way down.

**Comment by haus** [comment]
:+1:

**Comment by kylog** [comment]
@joshcooper thoughts?

**Comment by joshcooper** [comment]
It should be possible to specify `privatebindir` in the host configs. Beaker doesn't care if it's a setting it currently knows about or not. That way we don't have to fix the acceptance test as part of FACT-833, instead we just pull the pin and remove the `privatebindir` overrides from the host configs in one commit.

**Comment by kylog** [comment]
Retested with the new and improved beaker#master, reducing this to a one-line change.

**Comment by joshcooper** [comment]
```
$ be rake ci:test:aio SHA=25a146bb621c20f1878d0e14b66c235df4a0e969 CONFIG=config/nodes/precise.yaml
...
              - Test Case Summary for suite 'tests' -
       Total Suite Time: 8.89 seconds
      Average Test Time: 1.78 seconds
              Attempted: 5
                 Passed: 5
                 Failed: 0
                Errored: 0
                Skipped: 0
                Pending: 0
                  Total: 5

**Pull request merged**
