### PR TITLE
(FACT-2595) Refactored some tests to use the beaker which method

### PR DESCRIPTION
**Pull request by Filipovici-Andrei**
Refactored some acceptance tests to use the beaker which method that works when running tests on localhost.

### CODE REVIEW

**Comment by gimmyxd** [comment]
@Filipovici-Andrei Is this dependent on recent beaker changes? If yes, we should bump in gemspec the minimum beaker version that contains the changes.

**Comment by Filipovici-Andrei** [comment]
Yes, this is dependant on the beaker changes. I'll do the bump and run the ad-hoc.

**Comment by Filipovici-Andrei** [comment]
Jenkins please test this

**Comment by Filipovici-Andrei** [comment]
Jenkins please test this

**Comment by gimmyxd** [comment]
@Filipovici-Andrei Jenkins please test this defaults to redhat 7 and ubuntu 16.04. I see the changes also affect windows, so you should add some windows platforms to that command. Eg. `windows10ent-64a,windows2012r2-64a,windows2016-64a,windows2019-64a`

**Pull request merged**
