### PR TITLE
(FACT-1120) fix build on FreeBSD

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
@Magisus I believe linking dl here as no longer needed, as it was only used by the dynamic_library functionality (which has been moved to Leatherman). Mind double-checking and removing it if that's true?

**Comment by MikaelSmith** [comment]
I suspect it was needed for Debian, based on the commit history around https://github.com/puppetlabs/facter/commit/91fa9b69d74030c851fca42ce51b178ac6388788.

**Comment by Magisus** [comment]
Yeah doesn't look like it's needed anymore, we build fine without it. I remember adding that to leatherman when we moved dynamic_library. How do you want me to go about removing it (git-wise)?

**Comment by MikaelSmith** [comment]
Already a ticket, let's close this one and open a new PR that removes the POSIX_LIBRARIES stuff.

**Comment by Magisus** [comment]
We no longer need to link to dl, resolved here https://github.com/puppetlabs/facter/pull/1049.

**Comment by mmoll** [comment]
confirmed :+1:

**Pull request closed without merging**
