### PR TITLE
(docs) Improve docs template a bit

### PR DESCRIPTION
**Pull request by nfagerlund**
This PR adds type information, and lists the elements for map facts.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Was this meant to go into stable for the release?

**Comment by peterhuene** [comment]
@nfagerlund ^? I think the schema added the augeas fact since we split off stable, so we may need to cherry pick this to stable.

**Comment by peterhuene** [comment]
Never mind, it looks like that change is in stable.  I believe there's nothing currently in master that isn't in stable wrt to the schema.

**Comment by nfagerlund** [comment]
@peterhuene @MikaelSmith Awesome. Yeah, no, no need to have this in stable; I can generate facts from wherever and just pull the template in.

**Pull request merged**
