### PR TITLE
(FACT-3031) Report major/minor/patch on macOS

### PR DESCRIPTION
**Pull request by ccaviness**
See https://developer.apple.com/documentation/foundation/nsoperatingsystemversion?language=objc

On macOS 11:
```
$ facter os.macosx.version
{
  full => "11.3",
  major => "11",
  minor => "3",
  patch => "0"
}
$ facter --show-legacy | grep productversion
macosx_productversion => 11.3
macosx_productversion_major => 11
macosx_productversion_minor => 3
macosx_productversion_patch => 0
```

On macOS 10.15:
```
$ facter os.macosx.version
{
  full => "10.15.7",
  major => "10.15",
  minor => "7",
}
$ facter --show-legacy | grep productversion
macosx_productversion => 10.15.7
macosx_productversion_major => 10.15
macosx_productversion_minor => 7
```

### CODE REVIEW

**Comment by ccaviness** [comment]
I'm not sure if the change to `lib/facter/config.rb` is necessary. Testing locally without it seems to work fine, but it was a place I found a reference to the legacy facts so I added `_patch` there. Someone who understands the codebase would know better than me.

**Comment by GabrielNagy** [comment]
Hi @ccaviness, thanks for the contribution! :tada:

> I'm not sure if the change to `lib/facter/config.rb` is necessary.

That code part handles the block/cache groups for core facts, so it makes sense to have it there for people who want to block/cache their OS facts.

The code changes look good, but we'll need a new ticket to track this, as FACT-2914 handled the major version bug fix. This is more of an improvement since it adds a new fact. I'd appreciate it if you could file a new ticket and update your commit message with it.

Can you also update https://github.com/puppetlabs/facter/blob/main/lib/schema/facter.yaml#L1177-L1186 with the new fact?

Thank you!

**Comment by ccaviness** [comment]
Created FACT-3031 and updated the PR description. Also added the new fact to `facter.yaml`.

**Comment by ccaviness** [comment]
(I didn't change the name of my git branch, though, as git frightens and confuses me and frankly I'm impressed I managed to successfully add a file and change the commit message without completely messing everything up.)

**Comment by GabrielNagy** [comment]
jenkins please test this on osx1015-64a,osx11-64a

**Comment by GabrielNagy** [comment]
jenkins please test this on osx1015-64a,osx11-64a

**Review by GabrielNagy — APPROVED** [review]

**Pull request merged**
