### PR TITLE
Merge stable

### PR DESCRIPTION
**Pull request by branan**
This merges stable into master. There was a conflict in `exe/facter.cc`, between configurable facter and resolve order changes. @Magisus and @ahenroid could you please take a look at this and make sure it looks correct to both of you, since you made those changes originally

### CODE REVIEW

**Comment by branan** [comment]
Uhhhhh, I have no idea what triggered CLA bot here. I vote we ignore it?

**Comment by kylog** [comment]
Dueling bots. Woot! @MikaelSmith can/should we blocklist the web-flow user so the CLA bot doesn't comment on PRs with merge commits (of whatever exactly is happening here)?

**Comment by MikaelSmith** [comment]
Yes, probably should.

**Comment by Magisus** [comment]
This looks right to me. From what I can tell, Andy's changes seem untouched, and all my stuff is in there.

**Comment by ahenroid** [comment]
Sorry, slow responder. Yes, the merged facter.cc looks great. Merge it.

**Pull request merged**
