### PR TITLE
(PA-2183) Update acceptance tests to work with Beaker 4

### PR DESCRIPTION
**Pull request by ekinanp**

### CODE REVIEW

**Comment by ekinanp** [comment]
https://jenkins-master-prod-1.delivery.puppetlabs.net/view/__experimental/job/experimental_puppet-agent-extra_puppet-agent-integration-suite_adhoc-1.10.x/2/ shows a passing ad-hoc build, so this is good to go if the CI failures can be ignored.

**Comment by ekinanp** [comment]
Going to target this at 3.11.x instead.

**Comment by speedofdark** [comment]
Do you want to add the (main) tag so Travis passes?

**Comment by ekinanp** [comment]
I added the (maint) tag

**Comment by smcclellan** [comment]
Is that a (maint) commit or a (PA-2183) commit? I don't get why we need both prefixes.

**Comment by speedofdark** [comment]
To stop Travis from complaining about commit messages formatting.

**Comment by ekinanp** [comment]
@smcclellan Because Facter requires commits to either have (maint) or (FACT-<ticket_no>) prefixed to them. It's really a PA-2183 commit, the (maint) is to get CI to pass. I'm happy to remove (maint) if we're ok merging it w/ CI failing, should be fine since it's just acceptance tests.

**Comment by ekinanp** [comment]
I removed the maint commit title as it is misleading (this work does have a ticket), and the work is small enough that it is not worth creating an extra FACT ticket for it. Travis' commit checker can fail for this one.

**Comment by smcclellan** [comment]
I'd love to just fix Travis' commit checker. I can think of plenty of cases where we'd want to merge non-FACT tickets into facter (such as this one).

**Pull request merged**
