### PR TITLE
(FACT-2872) Added support for labeled secondary ips and inactive interfaces on linux platforms

### PR DESCRIPTION
**Pull request by Filipovici-Andrei**
**Problem:** 
On linux platforms interfaces were extracted using the 'ip -o address'. This didn't output the inactive interfaces.
Secondary IPs, were displayed only in the bindings/bindings6 section of the physical interface and not as a separate interface.
**Solution:**
Secondary IPs, if they have a label, will also be displayed as a separate interface.

Check for scope6 has been added in the facts/networking acceptance test.
Acceptance test for VLANs has been added.

### CODE REVIEW

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on all

**Comment by florindragos** [comment]
jenkins please test this on all

**Review by florindragos — APPROVED** [review]

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on amazon6-64a

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on amazon6-64a

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on amazon6-64a

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on amazon6-64a

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on amazon6-64a, amazon7-64a

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on amazon6-64a

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on amazon6-64a, amazon7-64a

**Comment by IrimieBogdan** [comment]
The resolver was reworked on #2219

**Pull request closed without merging**
