### PR TITLE
(FACT-1266) Remove leading dot from .gemspec.in

### PR DESCRIPTION
**Pull request by MikaelSmith**
The task that produces a tar file for a release ignores dot-files. This
is likely a property of the glob used when specifying files to tar. The
template file used to produce .gemspec is expected for CMake
configuration, so we shouldn't hide it anyway.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Requires https://github.com/puppetlabs/facter/pull/1217 to pass CI.

**Comment by MikaelSmith** [comment]
Rebased to fix CI.

**Comment by mmoll** [comment]
this is looking good, thanks! :+1:

**Comment by melissa** [comment]
Does this change actually work, and get the file into the tarball?

**Comment by MikaelSmith** [comment]
Looks like. Testing notes in https://tickets.puppetlabs.com/browse/FACT-1266.

**Pull request merged**
