### PR TITLE
(FACT-2872_2) Reimplement linux networking resolver

### PR DESCRIPTION
**Pull request by Filipovici-Andrei**

### CODE REVIEW

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on all

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on all

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on all

**Review by IrimieBogdan — APPROVED** [review]

**Comment by joshcooper** [comment]
CI failed on all Solarises (Solari?) with this change:

```
Expected /^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/ to match "".
```

I think it's because previously the networking.dhcp fact was reported correctly in puppet-agent#2b5f4eea0:

```
$ facter --json "networking.dhcp"
{
  "networking.dhcp": "10.32.22.9"
}
```

But now using puppet-agent#c5bed133e, it's empty:

```
$ facter networking --json
    {
      "networking": {
        "dhcp": "",
```

**Pull request merged**
