### PR TITLE
(FACT-1530) Update networking facts tests

### PR DESCRIPTION
**Pull request by LuvCurves**
Add support for Cisco XR, Huawei and s390x Redhat systems

### CODE REVIEW

**Comment by Magisus** [comment]
The version of these tests on stable differs somewhat significantly from that on master due to https://github.com/puppetlabs/facter/commit/66c0fd6ebdd639ef80745f39cbd29420026baed4. Does that commit fix some of the same problems as this one? If not, which structure (case statement versus a series of ifs) makes more sense?

**Comment by LuvCurves** [comment]
@Magisus Didn't realize STABLE and MASTER were not in sync for this file.  Let me modify this version to be a fixed version of what's in MASTER.

**Comment by LuvCurves** [comment]
@Magisus Updated to reflect the changes on master.
@kurtwall Ready for merge

**Comment by kurtwall** [comment]
👍

**Pull request merged**
