### PR TITLE
(maint) Bump version to 3.0.0

### PR DESCRIPTION
**Pull request by MikaelSmith**

### CODE REVIEW

**Comment by peterhuene** [comment]
Have we fixed all the jenkins jobs where having 3.0 (hence why it was changed back to 2.9 on master iirc) so that this is not a problem anymore?

**Comment by branan** [comment]
@peterhuene the commit message for setting it to 2.9 doesn't mention any issues, but @MikaelSmith was the one that wrote it

**Comment by MikaelSmith** [comment]
I don't see any issues. I don't remember having a good reason then either.

**Comment by kylog** [comment]
Can you bump lib/Doxyfile also?

**Comment by kylog** [comment]
Other than that :+1:

**Pull request merged**
