### PR TITLE
(maint) Use RapidJSON from Leatherman.

### PR DESCRIPTION
**Pull request by peterhuene**
Removing out of date RapidJSON library from the vendor directory and consuming
the RapidJSON library from Leatherman.

This required changes where the RapidJSON API was used.

### CODE REVIEW

**Comment by peterhuene** [comment]
Whoops, missed the GCE/AWS parsers.  Fixing.

**Comment by MikaelSmith** [comment]
:+1:

**Comment by MikaelSmith** [comment]
Does this make sense in stable?

**Comment by MikaelSmith** [comment]
I guess it should have no functional impact, so I could go either way.

**Comment by kylog** [comment]
:+1: on stable.

**Comment by kylog** [comment]
Also: is coveralls wedged?

**Comment by MikaelSmith** [comment]
Seems to be running, but not updating the status check.

**Pull request merged**
