### PR TITLE
(maint) Changelog for 4.0.30

### PR DESCRIPTION
**Pull request by oanatmaria**

### CODE REVIEW

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on aix61-POWERfa,aix71-POWERfa,aix72-POWERfa,amazon6-64a,amazon7-64a,debian8-64a,debian8-32a,debian9-64a,debian9-32a,debian10-64a,fedora30-64a,fedora31-64a,osx1014-64a,osx1015-64a,redhat5-64a,centos6-64a,centos6-32a,centos8-64a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,redhat8-64a,redhatfips7-64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,sles15-64a,solaris10-64a,solaris11-64a,solaris114-64a,ubuntu1404-64a,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1604-POWERa,ubuntu1804-64a,ubuntu2004-64a,windows10ent-64a,windows10ent-32a,windows2008r2-64a,windows2012r2-64a,windows2019_ja-64a,windows2016-64a,windows2019-64a,windowsfips2012r2-64a

**Comment by oanatmaria** [comment]
jenkins please test this on aix61-POWERfa,aix71-POWERfa,aix72-POWERfa,amazon6-64a,amazon7-64a,debian8-64a,debian8-32a,debian9-64a,debian9-32a,debian10-64a,fedora30-64a,fedora31-64a,osx1014-64a,osx1015-64a,redhat5-64a,centos6-64a,centos6-32a,centos8-64a,redhat7-64a,redhat7-POWERa,redhat7-AARCH64a,redhat8-64a,redhatfips7-64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,sles15-64a,solaris10-64a,solaris11-64a,solaris114-64a,ubuntu1404-64a,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1604-POWERa,ubuntu1804-64a,ubuntu2004-64a,windows10ent-64a,windows10ent-32a,windows2008r2-64a,windows2012r2-64a,windows2019_ja-64a,windows2016-64a,windows2019-64a,windowsfips2012r2-64a

**Comment by mihaibuzgau** [comment]
jenkins please test this on aix-6.1-ppc el-5-x86_64 el-5-i386 el-6-x86_64 el-6-i386 el-7-x86_64 el-7-ppc64le el-7-aarch64 el-8-x86_64 debian-8-amd64 debian-8-i386 debian-9-amd64 debian-9-i386 debian-10-amd64 fedora-30-x86_64 fedora-31-x86_64 osx-10.14-x86_64 osx-10.15-x86_64 redhatfips-7-x86_64 sles-11-x86_64 sles-11-i386 sles-12-x86_64 sles-12-ppc64le sles-15-x86_64 solaris-11-i386 solaris-11-sparc ubuntu-14.04-amd64 ubuntu-14.04-i386 ubuntu-16.04-amd64 ubuntu-16.04-i386 ubuntu-16.04-ppc64el ubuntu-18.04-amd64 ubuntu-20.04-amd64 windows-2012r2-x64 windows-2012r2-x86 windowsfips-2012r2-x64

**Comment by oanatmaria** [comment]
jenkins please test this on aix61-POWERa,debian8-64a,debian8-32a,debian9-64a,debian9-32a,fedora28-64a,fedora29-64a,osx1012-64a,osx1013-64a,osx1014-64a,redhat5-64a,centos6-64a,centos6-32a,redhat7-64a,redhat8-64a,redhatfips7-64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,sles15-64a,solaris10-64a,solaris114-64a,ubuntu140464a,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1804-64a,windows2016-64a,windows2019-64a

**Comment by oanatmaria** [comment]
jenkins please test this on aix61-POWERa,debian10-64a,debian8-64a,debian8-32a,debian9-64a,debian9-32a,fedora30-64a,fedora31-64a,osx1014-64a,osx1015-64a,redhat5-64a,centos6-64a,centos6-32a,redhat7-64a,redhat8-64a,redhatfips7-64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,sles15-64a,solaris10-64a,solaris11-64a,solaris114-64a,ubuntu140464a,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1804-64a,ubuntu2004-64a,windows2012r2-64a,windowsfips2012r2-64a

**Comment by oanatmaria** [comment]
jenkins please test this on aix61-POWERa,debian10-64a,debian8-64a,debian8-32a,debian9-64a,debian9-32a,fedora30-64a,fedora31-64a,osx1014-64a,osx1015-64a,redhat5-64a,centos6-64a,centos6-32a,redhat7-64a,redhat8-64a,redhatfips7-64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,sles15-64a,solaris10-64a,solaris11-64a,solaris114-64a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1804-64a,ubuntu2004-64a,windows2012r2-64a,windowsfips2012r2-64a

**Pull request merged**
