### PR TITLE
Use ip command in RHEL7 and derivatives to detect network interfaces

### PR DESCRIPTION
**Pull request by novakv**
Proposed change (for 2.x) is to use ip binary instead of ifconfig for detecting ip information in RHEL7 (and derivatives).

In RHEL7, ifconfig command is deprecated and it's not installed by default. Unless net-tools gets installed, facter does not return information related to network interfaces.

This incorporates patch proposed by @kstreitova (FACT-184) for detecting long interface names and changes to using ip command for looking up details of interfaces specified in existing REGEX_MAP.

@MikaelSmith Restriction to RHEL7 is based on your comment on older Linux versions in https://tickets.puppetlabs.com/browse/FACT-184

### CODE REVIEW

**Comment by novakv** [comment]
Dear Puppeteers,
Thank you for your email, I have now submitted the CLA.
I have a question regarding article no.7, which reads:"Should You wish to submit work that is not Your original creation, You may submit it to Puppet Labs separately from any Contribution, identifying the complete details of its source and of any license or other restriction (including, but not limited to, related patents, trademarks, and license agreements) of which [...]"
In my commit, I did include work which was not my creation.I have mentioned this in my comment and mentioned who is the original author. What else do I need to do?
Regards,Vanessa 


     On Monday, 30 March 2015, 20:00, puppetcla <notifications@github.com> wrote:
   

 Waiting for CLA signature by @novakv@novakv - We require a Contributor License Agreement (CLA) for people who contribute to Puppet, but we have an easy click-through license with instructions, which is available at https://cla.puppetlabs.com/Note: if your contribution is trivial and you think it may be exempt from the CLA, please post a short reply to this comment with details. http://docs.puppetlabs.com/community/trivial_patch_exemption.html—

**Comment by novakv** [comment]
Thanks for you answer. That is covered then, the original contibutor have signed the CLA. See https://github.com/puppetlabs/facter/pull/838#issuecomment-69734367

**Comment by MikaelSmith** [comment]
Thank your for the interest. As noted in https://tickets.puppetlabs.com/browse/FACT-184, this will be fixed in Facter 3, and a preview is available under the name CFacter in the Puppet 4 RC (https://puppetlabs.com/blog/release-candidate-open-source-puppet-4.0).

Also, the issue with `net-tools` was addressed in packaging for Facter 2.2, which is available in our RHEL 7 repositories (https://docs.puppetlabs.com/guides/puppetlabs_package_repositories.html#for-red-hat-enterprise-linux-and-derivatives).

If you are intent on addressing the issue in Facter 2.x for yourself (we would likely not deem this sufficient for a bug-fix release), a number of issues prevent us from merging it:
* The commit history includes a number of changes from Facter#master that need to be cleaned up. So your branch would need to be rebased to remove the unintended commits.
* The commits you added must be changed to follow the commit guidelines at https://github.com/puppetlabs/facter/blob/2.x/CONTRIBUTING.md.
* The fix itself should have spec tests updated, and an acceptance test added that runs on relevant systems to show that the networking facts work with your changes.

In it's current state this commit can't be merged, so we'll close it. If you undertake to address the issues above you can re-open the PR.

**Comment by MikaelSmith** [comment]
If you'd like to discuss this further, we have PR Community Triage Meetings on Wednesday for community members to join at 10am PDT (announced on IRC #puppet-dev) at links.puppetlabs.com/pr-triage.

**Comment by novakv** [comment]
In the meantime I realized that spec tests would need to be updated. Thank you for taking the time for a very informative answer, pointing out to all other issues with the pull request and telling me about PR Community Triage Meetings.
  


     On Tuesday, 31 March 2015, 20:46, Michael Smith <notifications@github.com> wrote:
   

 If you'd like to discuss this further, we have PR Community Triage Meetings on Wednesday for community members to join at 10am PDT (announced on IRC #puppet-dev) at links.puppetlabs.com/pr-triage.—

**Pull request closed without merging**
