### PR TITLE
(FACT-1111) Merge fixes to stable

### PR DESCRIPTION
**Pull request by MikaelSmith**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Waiting on https://jenkins.puppetlabs.com/view/All%20in%20One%20Agent/view/Master/view/Facter/ to verify the acceptance test is now fixed. @branan can you do a visual inspection that this looks right?

**Comment by branan** [comment]
@MikaelSmith visual inspection looks like a clean cherry-pick to me.

**Comment by MikaelSmith** [comment]
Jenkins CI passed.

**Comment by branan** [comment]
Confirmed this built and passed tests (since travis picked up the skip CI tag on the fixup commit)

**Pull request merged**
