### PR TITLE
(FACT-1505) Update CFPropertyList gem to 2.3.3

### PR DESCRIPTION
**Pull request by keeleysam**
https://tickets.puppetlabs.com/browse/FACT-1505

### CODE REVIEW

**Comment by michaeljs1990** [comment]
When i gem install this on mac it is not grabbing this dependency.

```
gem install facter
Fetching: facter-2.4.6.gem (100%)
Successfully installed facter-2.4.6
Parsing documentation for facter-2.4.6
Installing ri documentation for facter-2.4.6
Done installing documentation for facter after 1 seconds
1 gem installed
```

```
ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```

**Comment by MikaelSmith** [comment]
It appears the gemspec doesn't load the gem runtime dependencies. I'm not sure how to make that work.

**Comment by michaeljs1990** [comment]
Since I am able to reproduce locally I'll take a stab at fixing this.

**Comment by MikaelSmith** [comment]
This seems fine.

**Pull request merged**
