### PR TITLE
(FACT-1485) Fix Amazon Linux operating system release parsing

### PR DESCRIPTION
**Pull request by downsj2**
Facter 3 reverted behavior that was already fixed in facter 2.  See FACT-1485 for details.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
👍

**Comment by MikaelSmith** [comment]
Seems eligible for merging up to stable for a bug-fix release.

**Comment by downsj2** [comment]
@puppetcla I do not believe this patch is subject to copyright and that it should be exempt from the CLA.

a) It's one line of code, which is simply a copy of other members of the same map with slight changes.
b) Due to the addition of that map entry, some redundant code is then removed further down the function.

There's nothing creative or novel about this patch, it's just an expression of code which was already present.

**Comment by MikaelSmith** [comment]
Thanks, closing in favor of https://github.com/puppetlabs/facter/pull/1403.

**Pull request closed without merging**
