### PR TITLE
(maint) Update boost to 1.58

### PR DESCRIPTION
**Pull request by mhaskel**
This updates the boost version and also updates the libraries boost is
being built with.

### CODE REVIEW

**Comment by mhaskel** [comment]
This seems to be failing travis since the update is a RE ticket not FACT or maint, so let me know if I need to update that.

**Comment by peterhuene** [comment]
@mhaskel Could probably use `(maint)` for this.  Not sure if we want to loosen our restriction on having only `maint`, `FACT`, and `doc` tags.  @kylog?

**Comment by kylog** [comment]
I'd rather reference public tickets in the applicable public project if it's of interest to users, or use (maint). This isn't a user-facing thing so (maint) makes sense to me.

The reason we're excluding RE is because in the past some user-facing changes were sliding in referring to RE tickets, and RE is a private repo so no one external could see the backstory.

**Comment by mhaskel** [comment]
@peterhuene @kylog ok, thanks, updated!

**Comment by kylog** [comment]
Seems reasonable, but I haven't tried 1.58 on Windows. Ping @MikaelSmith.

**Comment by MikaelSmith** [comment]
I was for awhile until I realized we hadn't updated it. This should be fine.

**Comment by MikaelSmith** [comment]
Running a puppet-agent build against this to check it.

**Pull request merged**
