### PR TITLE
(FACT-1221) Add fallback for resolving total and free memory on SPARC

### PR DESCRIPTION
**Pull request by MikaelSmith**
On Solaris SPARC in our LDoms, kstat_read fails similar to FACT-909. Add a fallback to use when it fails, where we call kstat directly.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
This should be ready to go.

**Comment by MikaelSmith** [comment]
ping @whopper

**Comment by whopper** [comment]
:+1: going to build this on top of stable as a final pass in SPARC. I'll merge once I'm able to run it.

**Comment by whopper** [comment]
:+1: Tested on Sol 10/11 x86 and SPARC - works everywhere.

```
{
  swap => {
    available => "2.00 GiB",
    available_bytes => 2147475456,
    capacity => "0%",
    total => "2.00 GiB",
    total_bytes => 2147475456,
    used => "0 bytes",
    used_bytes => 0
  },
  system => {
    available => "1.95 GiB",
    available_bytes => 2088837120,
    capacity => "65.67%",
    total => "5.67 GiB",
    total_bytes => 6084788224,
    used => "3.72 GiB",
    used_bytes => 3995951104
  }
}

```

**Pull request merged**
