### PR TITLE
(FACT-1720) Use external weight for environment facts

### PR DESCRIPTION
**Pull request by branan**

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
Is there a way to add tests for this?

**Comment by branan** [comment]
@McdonaldSeanp There is a separate PR from QA that adds acceptance tests. I could look in to unit tests I guess

**Comment by McdonaldSeanp** [comment]
Yeah, I was just thinking for unit testing.

**Comment by McdonaldSeanp** [comment]
I'm +1 for merging this without unit tests due to timelines

**Pull request merged**
