### PR TITLE
Merge stable to master.

### PR DESCRIPTION
**Pull request by peterhuene**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
:+1:

**Comment by branan** [comment]
:+1: from me too, just waiting on appveyor

**Comment by branan** [comment]
```
C:\projects\facter\lib\tests\ruby\windows\ruby.cc:44:75: error: 'LIBFACTER_TESTS_DIRECTORY' was not declared in this scope
```

**Comment by peterhuene** [comment]
I'll push up a fix when I get home; at an event for my wife until later this evening.

**Comment by peterhuene** [comment]
@branan All fixed.

**Pull request merged**
