### PR TITLE
(maint) Do not rely on external networking for WSASetup validation

### PR DESCRIPTION
**Pull request by branan**
For FACT-1551, we added a test to ensure we had called WSASetup before
trying to resolve Ruby facts. As originally implemented, this test
required public network access and a functional external resource.

Most of this is not necessary to validate that WSA has been setup, and
makes the test more fragile. Instead, we can simply ensure that
creating and closing a socket proceeds without error.

### CODE REVIEW

**Comment by branan** [comment]
This is targeted at LTS, and should be merged up as we go

**Comment by MikaelSmith** [comment]
Put up another commit on top to comment out the fix related to this test, and let's see if it gets through AppVeyor.

**Comment by branan** [comment]
@MikaelSmith Sounds like a good plan. I want to see this go green as-is in appveyor/travis first, since I had some local failures that I think (hope) are related to our tests not being run on Arch all the time.

**Comment by branan** [comment]
Hmph, that's not good.

**Comment by branan** [comment]
OK, so it looks like despite Microsoft's docs, simply opening a socket isn't enough to fail this stuff. I'm gonna try some more things

**Comment by branan** [comment]
Fingers crossed that take three here will do the trick :fearful:

**Comment by MikaelSmith** [comment]
I think it might specifically be the hostname resolution that requires WSAStartup.

**Comment by branan** [comment]
@MikaelSmith THAT'S NOT WHAT MICROSOFT'S DOCS SAY, but I would totally believe it, and that makes this more of a pain :(

**Comment by branan** [comment]
I'm gonna close this for now - it's not turning out to be the quick fix I hoped it was, and it's not all that important. I'll play with it again another day.

**Pull request closed without merging**
