### PR TITLE
(FACT-854) Merge cfacter to facter/master

### PR DESCRIPTION
**Pull request by MikaelSmith**

### CODE REVIEW

**Comment by briancain** [comment]
clap

**Comment by whopper** [comment]
stuff

**Comment by MikaelSmith** [comment]
Passed checks. Anyone up for checking that the deletion and merge look right, and merging this behemoth?

**Comment by branan** [comment]
:+1:. Deletion and merge look correct to me.

**Comment by kylog** [comment]
:+1:

**Comment by bostjan** [comment]
I've signed CLA years ago, and if I try it again with my regular FOSS email (bostjan@*.si), it does not work, saying email has been taken.

I signed it with bostjan.skufca@*.si (same domain as above) for now, again, but I would like my github handle "bostjan" to be associated with email from the first paragraph of this message. Can you fix that?

**Comment by MikaelSmith** [comment]
@jeffmccune Anything left to be done about @bostjan's CLA?

**Pull request merged**
