### PR TITLE
(FACT-2887) Changed syscall for primary interface

### PR DESCRIPTION
**Pull request by sebastian-miclea**
Updated on how the primary interface is retrieved from **ip route get 1** to **ip route show default**

### CODE REVIEW

**Comment by sebastian-miclea** [comment]
Jenkins please test this on all

**Comment by sebastian-miclea** [comment]
Jenkins please test this on all

**Comment by sebastian-miclea** [comment]
Jenkins please test this on all

**Comment by kenyon** [comment]
What about the IPv6 part of FACT-2887?

**Comment by sebastian-miclea** [comment]
> What about the IPv6 part of FACT-2887?

I've created FACT-2895 for the new primary6 fact and we will scope it most likely in the next sprint. 
At the moment we are focusing on fixing some differences between Facter 3 and Facter 4. 
Also I closed this PR in favour of https://github.com/puppetlabs/facter/pull/2217

**Pull request closed without merging**
