### PR TITLE
(FACT-1929) Report disks serial numbers on Linux and FreeBSD

### PR DESCRIPTION
**Pull request by smortex**
This change add a `serial_number` attributes to the disks fact.

Implementation for Linux and FreeBSD is included (I do not have access to other operating systems):

```sh-session
romain@zappy ~/Projects/facter % uname 
FreeBSD
romain@zappy ~/Projects/facter % ./bin/facter disks
{
  ada0 => {
    model => "Samsung SSD 850 PRO 512GB",
    serial_number => "S250NXAG959927J",
    size => "476.94 GiB",
    size_bytes => 512110190592
  }
}
```

```sh-session
romain@vps ~/facter % uname
Linux
romain@vps ~/facter % ./bin/facter disks 
{
  sda => {
    model => "QEMU HARDDISK",
    serial_number => "drive-scsi0-0-0-0",
    size => "20.00 GiB",
    size_bytes => 21474836480,
    vendor => "QEMU"
  }
}
```

On FreeBSD, the information is directly provided by GEOM and the amount of changes is really small.

On Linux, the disks serial numbers are not exposed in `/sys/devices`  and cannot be retrieved by `blkid`, but we can rely on udev to get that information, so an optional dependency on udev was added for this purpose.

### CODE REVIEW

**Comment by GabrielNagy** [comment]
jenkins please test this on debian8-64a,debian8-32a,debian9-64a,debian9-32a,fedora28-64a,fedora29-64a,osx1012-64a,osx1013-64a,osx1014-64a,redhat5-64a,centos6-64a,centos6-32a,redhat7-64a,redhat8-64a,redhatfips7-64a,sles11-64a,sles11-32a,sles12-64a,sles12-POWERa,sles15-64a,solaris10-64a,solaris11-64a,solaris114-64a,ubuntu1404-64a,ubuntu1404-32a,ubuntu1604-64a,ubuntu1604-32a,ubuntu1804-64a,windows2016-64a,windows2019-64a

**Comment by smortex** [comment]
@GabrielNagy I guess your comment triggered the bunch of jenkins builds.  I see that **(6/6) Acceptance tests** has failed.  The system seems not to be publicly accessible, may you copy relevant information in this PR so that I can fix it?  Thanks!

**Comment by GabrielNagy** [comment]
Hi @smortex,

Thanks for your contribution! The failing job was transient, retriggering it fixed the problem.

If you squash your commits we can merge this.

**Comment by GabrielNagy** [comment]
You can also rebase the PR and commit on 3.13.x if you want it in the next 3.13 release.

**Comment by smortex** [comment]
@GabrielNagy commits squashed, rebased on top of the `3.13.x` branch and PR updated to target this branch.

Do you confirm that the commit will automagically be imported in future versions of facter (3.14+, 4.0+)?

Thanks!

**Comment by GabrielNagy** [comment]
@smortex yup, the commit will be promoted to master automatically after integration tests pass.

**Pull request merged**
