### PR TITLE
(maint) Update for GCC 4.9.2

### PR DESCRIPTION
**Pull request by MikaelSmith**
- Fix signed/unsigned comparisons
- Update Windows build dependencies

Also updates other build packages.

### CODE REVIEW

**Comment by peterhuene** [comment]
o.O with regards to those warnings; every one is a literal that can promoted to unsigned without any possibility of an incorrect comparison.  Also, I was building with GCC 4.9 on Arch for quite some time; is this warning coming only from Windows builds?

**Comment by MikaelSmith** [comment]
I was only testing on Windows, but I agree it seems overly pedantic.

**Comment by MikaelSmith** [comment]
I'll try a Linux build with 4.9.2 to compare.

**Comment by MikaelSmith** [comment]
I could also disable the warning.

**Comment by peterhuene** [comment]
Seems like a useful warning generally (especially when not comparing to positive signed literals), so I'm hesitant to disable it.  I can live with fixing up the warnings; curious as to why I wasn't seeing it on Linux though; perhaps it was changed in a minor release?

**Comment by MikaelSmith** [comment]
@stahnma should I relabel this [RE-4468](https://tickets.puppetlabs.com/browse/RE-4468)?

**Comment by peterhuene** [comment]
Should I merge or wait for response from @stahnma?

**Comment by kylog** [comment]
Please don't change the first token. The jira/git reconciliation script only knows about maint/docs/packaging and the project name (here FACT). So if there's some request to include an out-of-project jira reference, just put it after the first token.

Also AFAIK RE doesn't do any automated harvesting of RE ticket #s from git commits.

**Comment by MikaelSmith** [comment]
@haus isn't completely against it

**Comment by kylog** [comment]
That clarified nothing for me :)

**Comment by MikaelSmith** [comment]
I think wait for a response. I may rework this into two PRs, one for Boost/git/ruby, another for GCC and yaml-cpp.

**Comment by MikaelSmith** [comment]
Closed in favor of #954 until RelEng is ready to advance to GCC 4.9.2.

**Pull request closed without merging**
