### PR TITLE
(FACT-1864) Do not require el-derivatives to have minor versions

### PR DESCRIPTION
**Pull request by branan**
Previously, the facter tests asserted that any EL derivative must have
at least one `.` in its version number. This is incorrect for amzl2,
which reports its version simple as "2".

### CODE REVIEW

**Comment by McdonaldSeanp** [comment]
👍

**Comment by branan** [comment]
Jenkins please test this on amazon-7-64a

**Comment by McdonaldSeanp** [comment]
Jenkins please test this on amazon7-64a

**Comment by branan** [comment]
Jenkins please test this on amazon7-64a

**Pull request merged**
