### PR TITLE
(FACT-1872) Add support for dmi.product.uuid for Windows platforms

### PR DESCRIPTION
**Pull request by ScottGarman**

### CODE REVIEW

**Comment by ScottGarman** [comment]
This leatherman PR needs to be merged first: https://github.com/puppetlabs/leatherman/pull/282

This is a successful ad-hoc build of an agent package based on these PRs: https://jenkins-master-prod-1.delivery.puppetlabs.net/view/puppet-agent/view/ad-hoc/job/platform_puppet-agent-extra_puppet-agent-integration-suite_adhoc-ad_hoc/306/

**Comment by ScottGarman** [comment]
Note: the AppVeyor error is due to the wmi::uuid definition not being in leatherman yet, once that PR gets merged we can kick AppVeyor again to see it pass.

**Comment by speedofdark** [comment]
merged: puppetlabs/leatherman#282

**Comment by ScottGarman** [comment]
It looks like the AppVeyor build uses a released version of leatherman and not the HEAD of 1.4.x, so that test will continue to fail. Instead I refer reviewers to the ad-hoc agent build results that Enis replicated above, and the passing acceptance tests in Jenkins.

**Comment by ScottGarman** [comment]
This is blocked until AppVeyor is updated to use the appropriate branch of leatherman, otherwise it will fail in perpetuity after this PR is merged.

**Comment by ScottGarman** [comment]
This is no longer blocked and ready for merge!

**Pull request merged**
