### PR TITLE
(FACT-1537) Let's fix locales/ and get a good tarball

### PR DESCRIPTION
**Pull request by mckern**
Confirmed that this will fix the inability to build facter 3.5.0 from the release tarball

### CODE REVIEW

**Comment by ScottGarman** [comment]
:+1:

**Comment by glennsarti** [comment]
Should there be an acceptance test for this somewhere?

**Comment by mckern** [comment]
@glennsarti yes, but writing a test for tarball "correctness" is beyond the scope of this PR (and should realistically work for every other product we generate tarballs for). I was kicking around **how** last night, and I'll talk about it with you a bit today if you want?

**Comment by glennsarti** [comment]
Probably a better task for the facter maintainers to take up.  This just seemed to me that it should be testable somewhere so we don't repeat the mistake.  I'd be happy for a merge if it was ticketted elsewhere.

**Comment by glennsarti** [comment]
@mckern On a different note, the commit messages don't seem to follow the Contributing guidelines for this project. Would it be possible to get them reworded as per https://github.com/puppetlabs/facter/blob/master/CONTRIBUTING.md#making-changes ?

**Comment by mckern** [comment]
@glennsarti There was a sarcastic comment in here, but it didn't post. Instead I beefed up commit messages a bit.

**Comment by mckern** [comment]
> Probably a better task for the facter maintainers to take up. This just seemed to me that it should be testable somewhere so we don't repeat the mistake. I'd be happy for a merge if it was ticketted elsewhere.

I think that "did this produce a valid tarball" is a task that should be handled by RE, since it's par tof the functionality provided by the Packaging repo and isn't unique to any one project. I'll work on getting it ticketed out -- there's already some internal conversation around how to build these tarball snapshots and if that's even the right thing to do in the future.

**Comment by MikaelSmith** [comment]
Seems like it should go against stable. Mind rebasing?

**Comment by mckern** [comment]
@MikaelSmith done

**Pull request merged**
