### PR TITLE
Added disk_type field to disk fact

### PR DESCRIPTION
**Pull request by kozl**

### CODE REVIEW

**Comment by kozl** [comment]
I didn't quite understand how to label my PR, it has **feature** and **community** labels. Is there any chance  this being merged? I'll fix the tests!

**Comment by IrimieBogdan** [comment]
> I didn't quite understand how to label my PR, it has **feature** and **community** labels. Is there any chance this being merged? I'll fix the tests!

Hi @kozl 

Sure, we welcome contributions from the community. Please fix the test and add unit test. 

In order to see this fact in Facter's results you will also have to create a fact that calls this resolver. Have a look at https://github.com/puppetlabs/facter/blob/main/lib/facter/facts/linux/disks.rb you fact should be simpler I think, similar to https://github.com/puppetlabs/facter/blob/main/lib/facter/facts/linux/facterversion.rb

**Comment by kozl** [comment]
Ready to merge : )
I've extended existing fact 'disks', so I don't need to create another fact. Am i right?

**Comment by IrimieBogdan** [comment]
Jenkins please test this on all

**Comment by IrimieBogdan** [comment]
> Ready to merge : )
> I've extended existing fact 'disks', so I don't need to create another fact. Am i right?

Great! Looks good, you are right, there is no need to add a new fact. I have added a Jira [ticket](https://tickets.puppetlabs.com/browse/FACT-2844) and prepended it to your commit message. Feel free to add more details to the Jira ticket if you want.

**Review by IrimieBogdan — APPROVED** [review]

**Pull request merged**
