### PR TITLE
(FACT-1421) Add NO_BATCH_FILES option to cmake

### PR DESCRIPTION
**Pull request by McdonaldSeanp**
puppet-agent carries the batch files for all executables with the new move to
vanagon for windows projects, we will need an option to omit batch file
creation during installation of facter so there are not more than one set of
batch files. So this commit adds a NO_BATCH_FILES option for cmake that omits
those files.

The change has a double negative in order to preserve expected behavior if the
option is not specified

### CODE REVIEW

**Comment by kylog** [comment]
Can you move this ticket to FACT? Facter is an open-source project so we try to reference public jira projects. Thanks!!

**Comment by McdonaldSeanp** [comment]
👍 @kylog

**Comment by McdonaldSeanp** [comment]
I created https://tickets.puppetlabs.com/browse/FACT-1421 as the ticket for this

**Comment by MikaelSmith** [comment]
The double-negative isn't necessary, you can use `option` to specify a default. Like
```
option(INSTALL_BATCH_FILES "Install batch files on Windows" ON)
```

**Comment by McdonaldSeanp** [comment]
Yeah that makes more sense, updated

**Pull request merged**
