### PR TITLE
(FACT-1010) Fix inaccurate uptime on Solaris zones

### PR DESCRIPTION
**Pull request by MikaelSmith**
On Solaris zones - besides the default `global` zone - uptime in Facter
3 was inaccurate compared to Facter 2. This seems to reflect a bug in
Solaris related to querying kstat for uptime.

Change to calling `uptime` directly, which should be authoritative.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Need to test on Solaris still, but a simpler replacement for https://github.com/puppetlabs/facter/pull/1126.

**Comment by MikaelSmith** [comment]
I think the kstat method allowed more precision, uptime seems limited to minutes.

**Comment by MikaelSmith** [comment]
Verified on Solaris 10.

**Comment by branan** [comment]
:+1:

**Comment by MikaelSmith** [comment]
Also installed the package on Solaris 11 and verified there.

**Comment by kylog** [comment]
Nano-nit: but can you s/innacurate/inaccurate/ in the commit summary?

**Comment by MikaelSmith** [comment]
Done.

**Pull request merged**
