### PR TITLE
(doc) Add documentation for running a version from source

### PR DESCRIPTION
**Pull request by jagij**
I wanted to reproduce something with the source code as found on
github, but some google searches later I couldn't find anything useful

I got help through the ticket, but I could have made progress 2 days
earlier if I had found this info.

For reference: my ticket:
https://tickets.puppetlabs.com/browse/FACT-1810

Some other ticket that references the same steps:
https://tickets.puppetlabs.com/browse/FACT-567

### CODE REVIEW

**Comment by MikaelSmith** [comment]
This specifically applies to the 2.x branch. For newer code it's more complicated.

**Comment by jagij** [comment]
I read somewhere that the best way to get something documented on the internet is to put some false information up. But let's not do that :)

**Comment by branan** [comment]
I think we should be able to cherry-pick this to the 2.x README (although I really, really, REALLY want to kill off Facter 2).

We should also do some work to fully document the build/test process for Facter 3, since that's what most people using puppet-agent will have

**Comment by GabrielNagy** [comment]
Hi @jagij, thanks for taking the time to contribute to Facter!

Over the past year we've been super busy working on Facter 4 which is a complete rewrite of Facter 3 in Ruby. Facter 4 has been out for some time and we ship it with Puppet 7. It should be fully backwards compatible with Facter 2 and 3 so we encourage you to try it!

As such, we don't accept contributions to Facter 2 anymore. If this problem also manifests on Facter 3 or 4 please open a PR targeting the `3.x` (cfacter or Facter 3) or `main` (Facter 4) branch.

For now I'm closing the PR, if you have any further questions feel free to ping me or @puppetlabs/night-s-watch.

**Pull request closed without merging**
