### PR TITLE
(FACT-3163) Add support for OpenBSD

### PR DESCRIPTION
**Pull request by buzzdeee**
Most inspiration taken from FreeBSD, rest from other OS, and some own creations. Not all core facts supported, but makes puppet facts works well, as well as puppet agent --test

Developed/Tested on OpenBSD 7.2, AMD64, Puppet 7.20.0, Ruby 3.1.2

also disable RuboCop Metrics/PerceivedComplexity
and Metrics/CyclomaticComplexity
as suggested by @joshcooper

### CODE REVIEW

**Comment by buzzdeee** [comment]
new after messing up: https://github.com/puppetlabs/facter/pull/2529 #2529

**Comment by joshcooper** [comment]
I think the CI failures are due to a change in behavior with rspec-mocks. We had a similar problem in puppet, so I'll take a look.

**Comment by buzzdeee** [comment]
thanks @joshcooper 
 yay, all checks passed.

give me a bit, and I'll look into the unit tests

**Comment by buzzdeee** [comment]
yeah, going to squash them, once I'm done with it, I'll let you know when I think I'm good (:

**Comment by buzzdeee** [comment]
@joshcooper I think I'm done. 

All OpenBSD facts have tests, and all but the dhcp resolver. I didn't implement a full Module/Class there, only subclassed Facter::Resolvers::Networking and override the extract_dhcp method. There I don't know how to properly test it, I made a number of different attempts, but all failed in various ways. 

other changes from initial PR:

- add system_uptime facts I forgot
- fix networking.dhcp fact
- case insensitive match in facter/framework/detector/os_detector.rb

the last one I needed because when facter is installed with puppetserver gem install facter, it returned OpenBSD and it just didn't matched it. My final goal is to get puppetserver to run on OpenBSD to replace my dated puppet master based on puppet 5.

**Comment by klemensn** [comment]
It would be great to get this landed so we can finish up Puppet 7 (and eventually retire 5) on OpenBSD.

**Comment by bigio** [comment]
I am currently running Puppetserver 7.9.2 on OpenBSD with this diff in production and it's working fine.
Having this committed will ease the move to Puppet7 on OpenBSD.

**Comment by buzzdeee** [comment]
with the file loading change to 4.4, this was quite a hurdle to find. 
updated to the latest, seems to all working.
It would be really great to get this landed.

Also wondering why the FACTER queue in Jira is archived?

**Review by joshcooper — APPROVED** [review]

**Comment by joshcooper** [comment]
Thanks for you work on this @buzzdeee!

**Comment by joshcooper** [comment]
Sorry but this introduced order dependent spec failures and had to be reverted. You can reproduce the failure using:

```
$ rspec -fd './spec/facter/resolvers/openbsd/virtual_spec.rb[1:2:1]' './spec/facter/util/facts/posix/virtual_detector_spec.rb[1:1:12:1]' --order random:17181
```

**Comment by buzzdeee** [comment]
I'm looking

**Comment by buzzdeee** [comment]
Hi @joshcooper 

thanks for the rspec line to reproduce the issue.

with a certainty of about 80% I understand what went wrong, and tried to address it in #2642

**Pull request merged**
