### PR TITLE
(FACT-1650) change fqdn test to loop waiting for the hostname to update

### PR DESCRIPTION
**Pull request by ericldelaney**
On Solaris 11 the hostname(1) command returns before its completely changed in the
system and a call to hostname again can return the old name. This change queries
the hostname until its confirmed changed or tells you that it failed to change.

### CODE REVIEW

**Comment by ericldelaney** [comment]
tested on: arista4-32a, centos7-64a, ciscoxr-64a%7Bhypervisor=vmpooler%7D, cisconx-64a%7Bhypervisor=vmpooler%7D, cumulus25-64a, debian8-32a, fedora25-32a, oracle7-64a, osx1012-64a, redhat7-64a, scientific7-64a, sles12-64a, solaris11-64a, ubuntu1610-32a, windows10ent-32a, windows2016-6432a

**Comment by Magisus** [comment]
We're okay doing this loop on all systems even though only Solaris 11 has a problem? Doesn't bother me, just checking.

**Comment by branan** [comment]
I'd prefer to keep the code simpler by not gating it. On most systems it'll exit the loop after the first check anyway

**Comment by ericldelaney** [comment]
@Magisus it works as written on all platforms. I thought about just having it do something just for Solaris 11, but by going simple it tells you should any OS have problems changing the name and in general and we're probably .5 to .75 seconds faster because we're not doing the 1 second sleep on all the platforms regardless

**Comment by Magisus** [comment]
Sounds good.

**Pull request merged**
