### PR TITLE
(FACT-855) Test facter output against the schema

### PR DESCRIPTION
**Pull request by MikaelSmith**
Tests facter output against the schema to confirm that the reported
facts are in the schema and match the specified type.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Depends on #890

**Comment by MikaelSmith** [comment]
Blocked on #892 finishing packaging so I can verify the test.

**Comment by MikaelSmith** [comment]
Validated against an uberbuild of #892

**Comment by peterhuene** [comment]
:+1:

**Pull request merged**
