### PR TITLE
(FACT-1525) Add pages_to_bytes helper in AIX memory resolver

### PR DESCRIPTION
**Pull request by ekinanp**
Previously, we would compute the number of bytes from a given number
of pages as `<num_pages> * PAGE_SIZE`. The problem is that if `<num_pages>`
is not a 64 bit numeric type, then the expression's value would be evaluated
as a uint so that large byte values would overflow. This would cause
Facter to report overflowed values for the swapsize and swapsize_mb facts
since the `size` and `free` fields of the pginfo struct are uints.

We could fix this by just casting these uints to uint64_t in the
multiplication. It's cleaner, however, to just add a helper that
converts pages to bytes to encapsulate the casting and the conversion.

### CODE REVIEW

**Comment by ekinanp** [comment]
This PR has one commit that will need to be reverted. I created it to replicate the overflow situation that might be causing the customer's issue. It looks like overflow is indeed an issue. When I compute `swapsize` fact without the "fix" commit on an AIX 7.1 VM, here's what I get:
```
[0] [AIX] root@aix71-4:~/facter # /opt/puppetlabs/puppet/bin/facter --query swapsize --debug
2018-07-31 19:23:21.650986 INFO  puppetlabs.facter - executed with command line: --query swapsize --debug.
2018-07-31 19:23:21.654407 INFO  leatherman.ruby:137 - ruby loaded from "/opt/puppetlabs/puppet/lib/libruby.so.2.4.4".
2018-07-31 19:23:21.740532 INFO  leatherman.ruby:186 - using ruby version 2.4.4
2018-07-31 19:23:21.741522 INFO  puppetlabs.facter - requested queries: swapsize.
2018-07-31 19:23:21.742292 DEBUG puppetlabs.facter - fact "facterversion" has resolved to "3.11.4".
2018-07-31 19:23:21.742926 DEBUG puppetlabs.facter - fact "aio_agent_version" has resolved to "5.5.4.49".
2018-07-31 19:23:21.743820 DEBUG leatherman.file_util:65 - Error reading file: No such file or directory
2018-07-31 19:23:21.746123 DEBUG puppetlabs.facter - loading all custom facts.
2018-07-31 19:23:21.746765 DEBUG puppetlabs.facter - loading custom fact directories from config file
2018-07-31 19:23:21.747520 DEBUG puppetlabs.facter - searching "/opt/puppetlabs/facter/facts.d" for external facts.
2018-07-31 19:23:21.748274 DEBUG puppetlabs.facter - skipping external facts for "/etc/facter/facts.d": No such file or directory
2018-07-31 19:23:21.748988 DEBUG puppetlabs.facter - skipping external facts for "/etc/puppetlabs/facter/facts.d": No such file or directory
2018-07-31 19:23:21.749609 DEBUG puppetlabs.facter - no external facts were found.
2018-07-31 19:23:21.750272 DEBUG puppetlabs.facter - resolving memory facts.
2018-07-31 19:23:21.751135 DEBUG puppetlabs.facter - swap_total = 36130816
2018-07-31 19:23:21.751761 DEBUG puppetlabs.facter - swap_free = 36130816
2018-07-31 19:23:21.752569 DEBUG puppetlabs.facter - fact "memoryfree" has resolved to "2.70 GiB".
2018-07-31 19:23:21.753229 DEBUG puppetlabs.facter - fact "memoryfree_mb" has resolved to 2768.7.
2018-07-31 19:23:21.753871 DEBUG puppetlabs.facter - fact "memorysize" has resolved to "8.00 GiB".
2018-07-31 19:23:21.754510 DEBUG puppetlabs.facter - fact "memorysize_mb" has resolved to 8192.
2018-07-31 19:23:21.755167 DEBUG puppetlabs.facter - fact "swapfree" has resolved to "34.46 MiB".
2018-07-31 19:23:21.755817 DEBUG puppetlabs.facter - fact "swapfree_mb" has resolved to 34.457.
2018-07-31 19:23:21.756456 DEBUG puppetlabs.facter - fact "swapsize" has resolved to "34.46 MiB".
2018-07-31 19:23:21.757095 DEBUG puppetlabs.facter - fact "swapsize_mb" has resolved to 34.457.
2018-07-31 19:23:21.757736 DEBUG puppetlabs.facter - fact "memory" has resolved to {
  swap => {
    available => "34.46 MiB",
    available_bytes => 36130816,
    capacity => "0%",
    total => "34.46 MiB",
    total_bytes => 36130816,
    used => "0 bytes",
    used_bytes => 0
  },
  system => {
    available => "2.70 GiB",
    available_bytes => 2903191552,
    capacity => "66.20%",
    total => "8.00 GiB",
    total_bytes => 8589934592,
    used => "5.30 GiB",
    used_bytes => 5686743040
  }
}.
34.46 MiB
```

As you can see, the `swapsize` should really be something like `16000 MiB`.

**Comment by ekinanp** [comment]
With the fix, here's what running facter looks like:
```
[0] [AIX] root@aix71-4:~/facter # /opt/puppetlabs/puppet/bin/facter --query swapsize --debug
2018-07-31 19:26:20.474373 INFO  puppetlabs.facter - executed with command line: --query swapsize --debug.
2018-07-31 19:26:20.477982 INFO  leatherman.ruby:137 - ruby loaded from "/opt/puppetlabs/puppet/lib/libruby.so.2.4.4".
2018-07-31 19:26:20.565764 INFO  leatherman.ruby:186 - using ruby version 2.4.4
2018-07-31 19:26:20.566783 INFO  puppetlabs.facter - requested queries: swapsize.
2018-07-31 19:26:20.567569 DEBUG puppetlabs.facter - fact "facterversion" has resolved to "3.11.4".
2018-07-31 19:26:20.568216 DEBUG puppetlabs.facter - fact "aio_agent_version" has resolved to "5.5.4.49".
2018-07-31 19:26:20.569578 DEBUG leatherman.file_util:65 - Error reading file: No such file or directory
2018-07-31 19:26:20.572185 DEBUG puppetlabs.facter - loading all custom facts.
2018-07-31 19:26:20.572823 DEBUG puppetlabs.facter - loading custom fact directories from config file
2018-07-31 19:26:20.573589 DEBUG puppetlabs.facter - searching "/opt/puppetlabs/facter/facts.d" for external facts.
2018-07-31 19:26:20.574364 DEBUG puppetlabs.facter - skipping external facts for "/etc/facter/facts.d": No such file or directory
2018-07-31 19:26:20.575105 DEBUG puppetlabs.facter - skipping external facts for "/etc/puppetlabs/facter/facts.d": No such file or directory
2018-07-31 19:26:20.575772 DEBUG puppetlabs.facter - no external facts were found.
2018-07-31 19:26:20.576452 DEBUG puppetlabs.facter - resolving memory facts.
2018-07-31 19:26:20.577488 DEBUG puppetlabs.facter - swap_total = 17216000000
2018-07-31 19:26:20.578119 DEBUG puppetlabs.facter - swap_free = 17216000000
2018-07-31 19:26:20.578943 DEBUG puppetlabs.facter - fact "memoryfree" has resolved to "2.68 GiB".
2018-07-31 19:26:20.579597 DEBUG puppetlabs.facter - fact "memoryfree_mb" has resolved to 2742.77.
2018-07-31 19:26:20.580233 DEBUG puppetlabs.facter - fact "memorysize" has resolved to "8.00 GiB".
2018-07-31 19:26:20.580866 DEBUG puppetlabs.facter - fact "memorysize_mb" has resolved to 8192.
2018-07-31 19:26:20.581506 DEBUG puppetlabs.facter - fact "swapfree" has resolved to "16.03 GiB".
2018-07-31 19:26:20.582196 DEBUG puppetlabs.facter - fact "swapfree_mb" has resolved to 16418.5.
2018-07-31 19:26:20.582844 DEBUG puppetlabs.facter - fact "swapsize" has resolved to "16.03 GiB".
2018-07-31 19:26:20.583487 DEBUG puppetlabs.facter - fact "swapsize_mb" has resolved to 16418.5.
2018-07-31 19:26:20.584159 DEBUG puppetlabs.facter - fact "memory" has resolved to {
  swap => {
    available => "16.03 GiB",
    available_bytes => 17216000000,
    capacity => "0%",
    total => "16.03 GiB",
    total_bytes => 17216000000,
    used => "0 bytes",
    used_bytes => 0
  },
  system => {
    available => "2.68 GiB",
    available_bytes => 2875998208,
    capacity => "66.52%",
    total => "8.00 GiB",
    total_bytes => 8589934592,
    used => "5.32 GiB",
    used_bytes => 5713936384
  }
}.
16.03 GiB
```

We see that the right value is calculated (the log indicates that `swap_total` and `swap_free` are `17216000000` bytes, which is exactly `17216 MB`).

**Comment by ekinanp** [comment]
Marking this as blocked not b/c it isn't ready for review, but as a reminder to revert the "Replicate customer issue" commit before merging.

**Comment by ekinanp** [comment]
It's kind of weird that my `swapsize` of `34.46 MiB` doesn't match the customer's reported `832 MiB` in the ticket. I think unsigned integer overflow is defined in C++? Dunno. But it does seem like overflow is definitely an issue.

**Comment by caseywilliams** [comment]
Approved pending test commit removal

**Comment by branan** [comment]
LGTM once the testing code is removed

**Comment by ekinanp** [comment]
Testing code has been removed.

**Pull request merged**
