### PR TITLE
(FACT-1155) Fix libfacter unit tests under Solaris.

### PR DESCRIPTION
**Pull request by peterhuene**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Has this been tested on Solaris?

**Comment by haus** [comment]
I can try this on my build this morning.

**Comment by haus** [comment]
Oops...I'm building off of master currently. Let me see if I can just build stable instead easily.

**Comment by haus** [comment]
```
===============================================================================
All tests passed (10549 assertions in 66 test cases)
```

**Comment by peterhuene** [comment]
:+1: thanks @haus!

**Comment by MikaelSmith** [comment]
Way more complicated, but looks fair to me. Is there the possibility of a significant performance hit? Would we want to limit this to only Solaris?

**Comment by peterhuene** [comment]
I don't think this will hurt performance much; the groups do end up getting cached.  Given that Solaris may not be the only platform affected (AIX?), I'd prefer to just use `stat` over #ifdef'ing.

**Pull request merged**
