### PR TITLE
(FACT-1087) Add acceptance tests to validate SLES 10, 11 and 12

### PR DESCRIPTION
**Pull request by whopper**
This commit adds a new fact-based acceptance test to validate
critical facts on SLES 10, 11 and 12.

### CODE REVIEW

**Comment by whopper** [comment]
Validating SLES 10 would be trivial, but I didn't because A) I'm not sure if we really care, and B) Beaker is choking on a curl call requiring commandline input to continue, so I wasn't able to properly test.

**Comment by ghoneycutt** [comment]
SLES10 is still supported until July 2016. Would appreciate validating on that platform as I'm still managing thousands of them.

**Comment by whopper** [comment]
@ghoneycutt can do!

**Comment by ghoneycutt** [comment]
Thanks @whopper  !!

**Comment by MikaelSmith** [comment]
How can I go about running these tests?

**Comment by whopper** [comment]
@MikaelSmith right now, you can do a puppet-agent vanagon build for SLES, install the resulting package on a SLES vmpooler VM, and run something like:
```
bundle exec beaker --hosts ./config/nodes/hosts_preserved.yaml --options config/git/options-no-provision.rb --no-provision --keyfile ~/.ssh/id_rsa-acceptance --preserve-hosts onfail --tests ./tests/facts
```

... where `hosts_preserved.yaml` has a config for a pre-provisioned SLES box, like so:

```
HOSTS:
  axrfkdtfmoh7c56.delivery.puppetlabs.net:
   roles:
   - agent
   platform: sles-11-x86_64
   hypervisor: vcloud
   template: sles-11-x86_64

```

**Pull request merged**
