### PR TITLE
(FACT-853) Fix packaging after move to facter

### PR DESCRIPTION
**Pull request by MikaelSmith**
Rename cfacter packaging to facter.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Ran through packaging job http://jenkins-release.delivery.puppetlabs.net/job/facter-packaging-2015-03-20-14-41-22-88f6455052a31941ada852252403813495be1a99.

**Comment by kylog** [comment]
@melissa or @haus is `changelog.erb` live even in ruby facter? The last update was for facter 1.7.2 and it has some typos, etc so I'm wondering if it's abandoned.

**Comment by melissa** [comment]
@kylog it hasn't been updated in a while, and doesn't need to be updated because of the automation. We do need to keep that file though. The history in it is kind of arbitrary though.

**Comment by MikaelSmith** [comment]
ext/redhat/facter.spec.erb also had changelog history in it. We might just remove all the old facter stuff.

**Comment by MikaelSmith** [comment]
@kylog @melissa Any objection if I just remove everything except the generated changelog entry? The rest of it is severely out of date.

**Comment by melissa** [comment]
@MikaelSmith no objection from me

**Comment by kylog** [comment]
@MikaelSmith yep sounds good.

**Comment by MikaelSmith** [comment]
Can ignore CI on this one.

**Comment by melissa** [comment]
:+1:

**Comment by MikaelSmith** [comment]
Build running at //jenkins-release.delivery.puppetlabs.net/job/facter-packaging-2015-03-20-15-16-27-a66d761850f477e9fd280a26d8d3f302692e4bd2

**Comment by MikaelSmith** [comment]
Build finished successfully.

**Pull request merged**
