### PR TITLE
(FACT-1130) Install facter.rb into vendorlibdir instead of vendordir

### PR DESCRIPTION
**Pull request by jasperla**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
@haus how does this affect our package builds?

**Comment by MikaelSmith** [comment]
This seems like it would be fine, but we'd prefer to make it configurable.

**Comment by haus** [comment]
@MikaelSmith it will load fine, but look out of place and all alone in the package. I agree, making it configurable would be ideal here.

**Comment by MikaelSmith** [comment]
Having a flag like RUBY_LIB_INSTALL (setup  similar to https://github.com/puppetlabs/facter/blob/master/CMakeLists.txt#L18-L19) that defaults to vendorlibdir if not set should work.

**Comment by jasperla** [comment]
Here we go :)

**Comment by MikaelSmith** [comment]
:+1:

**Pull request merged**
