### PR TITLE
(FACT-1610) Parse 64-bit AIX Volume Group IDs

### PR DESCRIPTION
**Pull request by branan**
Previously, Facter assumed the VGs would have a 128-bit ID. This is
only true for volumes created this century. Older versions of AIX
created groups with 64-bit IDs.

This change updates AIX volume ID parsing to support these shorter
IDs.

### CODE REVIEW

**Comment by Magisus** [comment]
Looks right to me. I don't suppose there's a meaningful way to add tests for this?

**Comment by branan** [comment]
@Magisus nah. We really should have structured facter better so that logic like this is easily unit-tested. Unfortunately, it's not :(

**Comment by Magisus** [comment]
Yeah that's what I saw too, looking at the tests. Oh well, LGTM then 👍

**Comment by ScottGarman** [comment]
:+1:

**Comment by er0ck** [comment]
i love the 90s

**Pull request merged**
