### PR TITLE
(FACT-2915) Break linux networking resolver into multiple classes

### PR DESCRIPTION
**Pull request by Filipovici-Andrei**
The linux networking resolver grew too large and this PR 
breaks it down into: 
Networking,
SocketParser,
Dhcp,
RoutingTable

### CODE REVIEW

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on all

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on all

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on all

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on all

**Review by sebastian-miclea — APPROVED** [review]

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on all

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on all

**Comment by Filipovici-Andrei** [comment]
jenkins please test this on all

**Pull request merged**
