### PR TITLE
(FACT-805) use /etc/os-release to identify CoreOS

### PR DESCRIPTION
**Pull request by jumanjiman**
It is possible to run an unprivileged docker container on CoreOS
with selective mounts (incl. `-v /etc/os-release:/etc/os-release:ro`)
and have the puppet agent *inside* the container affect the host
*outside* the container.

It is also nice to be able to run such a container on CoreOS
merely to report inventory to the puppet master and puppetdb
to track inventory.

Before this commit, Facter falls back to generic Linux facts:

    # facter -p | egrep -i '^(os|operating)'
    operatingsystemmajrelease => 3
    operatingsystemrelease => 3.18.2
    os => {"family"=>"Linux", "release"=>{"major"=>"3", "minor"=>"18", "full"=>"3.18.2"}}
    osfamily => Linux

After this commit, Facter uses /etc/os-release when /etc/os-release
is mounted inside the container and recognizes the underlying
coreos inventory data. This commit is based on the existing
logic for Cumulus Linux and adds corresponding rspec tests.

    # facter -p | egrep -i '^(os|operating)'
    operatingsystem => CoreOS
    operatingsystemmajrelease => 575
    operatingsystemrelease => 575.0.0
    os => {"name"=>"CoreOS", "family"=>"CoreOS", "release"=>{"major"=>"575", "minor"=>"0", "full"=>"575.0.0"}}
    osfamily => CoreOS

New unit tests:

    Facter::Operatingsystem::Linux
      Operatingsystemmajrelease key
        on CoreOS operatingsystems
          should be derived from operatingsystemrelease

    Facter::Util::Operatingsystem
      reading the os-release file
        correctly parses the file on CoreOS Linux

It would be nice to DRY up the code so that Cumulus and CoreOS
use a common implementation, but this commit attempts to keep
the logic separate to avoid touching any existing rspec for Cumulus.

### CODE REVIEW

**Comment by kylog** [comment]
@peterhuene should we do the same in native facter.

**Comment by kylog** [comment]
Holding off on merge of this pending our sorting out timeline for facter 3. And we hope to sort that out in the next week or so.

**Comment by peterhuene** [comment]
@kylog I've created https://tickets.puppetlabs.com/browse/CFACT-215 to track this issue in libfacter.

**Comment by jumanjiman** [comment]
i've  created https://github.com/puppetlabs/cfacter/pull/303 as an attempt to learn cfacter code base and resolve cfact-215. i welcome any advice or tips.

**Comment by jumanjiman** [comment]
update: the facts here and in cfacter have identical values.

**Comment by jumanjiman** [comment]
rebased on upstream/master

**Comment by kylog** [comment]
@jumanjiman sorry for the churn on the facter side (and thanks for the contribution on the cfacter side). We're hoping to get facter 3 out pretty soon (on the order of weeks rather than months) so this may have been overtaken by events.

However, if you're still interested in getting this into the 2.x line, can you re-target at the facter/2.x branch?

Backstory: https://groups.google.com/forum/#!msg/puppet-dev/tBqHZB9M308/QqdaldMsJlkJ

Thanks again for the contributions!

**Comment by jumanjiman** [comment]
> can you re-target at the facter/2.x branch?

done!

https://github.com/puppetlabs/facter/pull/866 since GH doesn't enable to retarget existing PRs

**Comment by kylog** [comment]
> done!
>
> #866 since GH doesn't enable to retarget existing PRs

That was fast. Thanks!

And yeah re-targeting existing PRs has been on my GH list for a while ....

**Comment by kylog** [comment]
Closing this one in favor of #866.

**Comment by jumanjiman** [comment]
> Backstory: https://groups.google.com/forum/#!msg/puppet-dev/tBqHZB9M308/QqdaldMsJlkJ

many thanks for the ref.
helpful.

**Pull request closed without merging**
