### PR TITLE
(FACT-2704) change all acceptance to risk:high

### PR DESCRIPTION
**Pull request by gimmyxd**

### CODE REVIEW

**Comment by gimmyxd** [comment]
needs rebase after https://github.com/puppetlabs/facter/pull/1978 is merged

**Comment by florindragos** [comment]
Jenkins please test this on all

**Comment by florindragos** [comment]
Jenkins please test this on all

**Comment by florindragos** [comment]
Jenkins please test this on all

**Comment by florindragos** [comment]
Jenkins please test this on all

**Comment by florindragos** [comment]
Jenkins please test this on all

**Comment by florindragos** [comment]
Jenkins please test this on all

**Comment by gimmyxd** [comment]
acceptance failure is related to: https://tickets.puppetlabs.com/browse/FACT-2723

**Comment by florindragos** [comment]
Jenkins please test this on all

**Comment by florindragos** [comment]
Jenkins please test this on all

**Comment by florindragos** [comment]
Jenkins please test this on all

**Comment by gimmyxd** [comment]
Jenkins please test this on all

**Comment by gimmyxd** [comment]
Jenkins please test this on all

**Comment by gimmyxd** [comment]
Jenkins please test this on all

**Comment by florindragos** [comment]
Jenkins please test this on all

**Review by Filipovici-Andrei — APPROVED** [review]

**Pull request merged**
