### PR TITLE
(FACT-1591) add TestRail numbers and missing teardown code

### PR DESCRIPTION
**Pull request by ericldelaney**
Add TestRail number to the associated test_name strings
While I was there I added teardown code for a couple missing items
tested on Linux and windows

### CODE REVIEW

**Comment by Magisus** [comment]
I was under the impression you didn't have to do teardown on directories created with tmpdir?

**Comment by ericldelaney** [comment]
Good question on tmpdir(), looking at the code we create a directory with a random name, but I don't know that anything will clean up the file or directory created. Which I guess on a VM isn't a problem per say. Probably the biggest problem would be on AIX where you might get the same file/directory, but your chances are probably pretty low.

    execute("rndnum=${RANDOM} && mkdir /tmp/#{name}.${rndnum} && echo /tmp/#{name}.${rndnum}")

**Comment by kurtwall** [comment]
@Magisus I delete temp dirs created using `tmpdir` during `teardown` because that's the prior art I encountered when I first started writing beaker tests. I'm sure I just assumed it was required, but I have no idea if that is actually the case. The name `tmpdir` notwithstanding, of course.

**Comment by Magisus** [comment]
Thanks for the info! I was curious because I wrote a lot of these tests originally.

**Pull request merged**
