### PR TITLE
(FACT-1504) Use GetTickCount64 as an uptime metric for windows platof…

### PR DESCRIPTION
**Pull request by jsane**
…orms

The earlier metric was unreliable and also stopped working altogether
(uptime fact on windows comes as empty) causing CI failures.
We now use GetTickCount64 instead which offers better resolution
and is available on all supported windows platforms.

### CODE REVIEW

**Comment by ekinanp** [comment]
jenkins please test this on windows2012r2-64a

**Comment by jsane** [comment]
Wondering if the above build step failure is my doing (compile error in an unrelated file). My 3.6.x branch was uptodate when I introduced the changes. I will attempt a local build but wanted to check if this looks familiar).
...
CMakeFiles/libfactersrc.dir/src/ruby/ruby.cc.o -c /var/tmp/tmp.LdYq1x2Jw8/facter/lib/src/ruby/ruby.cc
13:33:35 /var/tmp/tmp.LdYq1x2Jw8/facter/lib/src/ruby/module.cc: In lambda function:
13:33:35 /var/tmp/tmp.LdYq1x2Jw8/facter/lib/src/ruby/module.cc:874:22: error: 'const struct leatherman::ruby::api' has no member named 'is_fixednum'
13:33:35              if (ruby.is_fixednum(timeout_option)) {
13:33:35                       ^
13:33:37 make[3]: *** [lib/CMakeFiles/libfactersrc.dir/src/ruby/module.cc.o] Error 1
...

**Comment by MikaelSmith** [comment]
That may need a different Leatherman version.

**Comment by MikaelSmith** [comment]
Leatherman 1.0.0 removed is_fixednum, so you want the 0.12.x line.

**Comment by jsane** [comment]
Pl disregard (this was meant for 3.6.x and not master). Sorry -dont know how I messed :-(

**Pull request closed without merging**
