### PR TITLE
Revert "(FACT-380) Use the interface of the default route for network facts"

### PR DESCRIPTION
**Pull request by branan**
This update was more breaking than we anticipated (see comments on FACT-380, but also FACT-1316 which was filed almost immediately)

For users that really need the new behavior, Facter 3 provides the new behavior.

This reverts commit ec73549be0c26aab40a8968330726b369ab080f7.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
:+1:

**Comment by MikaelSmith** [comment]
Is there a new ticket for this change going into 2.4.6?

**Comment by branan** [comment]
@MikaelSmith not currently. This is the first time I've had to deal with a revert first-hand, not really sure what our general policy/plan is here

**Comment by MikaelSmith** [comment]
Probably associate it with FACT-1316 with a fix target of 2.4.6. /cc @kylog

**Comment by kylog** [comment]
We don't have a general policy/precedent for this type of scenario, but, yeah, that makes sense to me here.

**Pull request merged**
