### PR TITLE
(FACT-1185) Add Solaris 10/11 SPARC node defs

### PR DESCRIPTION
**Pull request by johnduarte**
This commit adds node definitions for solaris sparc 10 and 11
agents using the SPARC architecture.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
:+1: we'll want to add these to Puppet and Hiera as well.

**Comment by joshcooper** [comment]
I noticed these files don't start with `---`, should theyl? Also they don't have the `.yaml` extension like we do with other files.

**Comment by MikaelSmith** [comment]
I guess others start with `---`, might be nice to add it to the existing Solaris files as well.

**Comment by johnduarte** [comment]
Solaris yaml files updated per comments from @joshcooper and @MikaelSmith

**Pull request merged**
