### PR TITLE
(docs) Split the facts reference into "modern" and "legacy" sections. 

### PR DESCRIPTION
**Pull request by nfagerlund**
This came out of some discussion in chat, where some people wanted to emphasize even more heavily that Puppet Labs would prefer that people use the new structured facts. 

I'm expecting we'll go back and forth a bit on wording, but wanted to get this up there to show it's really pretty easy to do.

### CODE REVIEW

**Comment by gguillotte** [comment]
Looks like Facter's Travis still prefers `(doc)` over `(docs)`.

**Comment by nfagerlund** [comment]
Aww, boo. Does someone with Travis access want to take a look at that? For other projects, I think we decided to allow both (doc) and (docs), with the latter being preferred due to precedent.

**Comment by MikaelSmith** [comment]
It should allow both.

**Comment by nfagerlund** [comment]
Ping — what do y'all think about splitting the list into two? And about the wording?

**Comment by MikaelSmith** [comment]
Seems like a sensible organization. If we have them split up like that, does it make sense to mention they're hidden for every fact?

**Comment by gguillotte** [comment]
We could cut it, though it might still make sense to note that in the fact
as some links point directly to the fact's heading.

**Comment by MikaelSmith** [comment]
Ok, that seems like a good reason. I could see using a more subtle design to show something that applies to the whole section, and is visible from any point in that section, but I'm not sure how easy that is.

**Comment by gguillotte** [comment]
Maybe add a section on the page that officially notes the facts are
deprecated, why, what the effects are, and how to work around it. Then we
just add a one-word link to that section instead of the repetitive sentence.

**Comment by MikaelSmith** [comment]
Not deprecated.

And yeah, a small link back to the header of the section could cover that.

**Comment by joshcooper** [comment]
Let's wait to merge until puppet-agent 1.2.7 goes out

**Comment by nfagerlund** [comment]
Works for me.

**Comment by MikaelSmith** [comment]
I think we could merge as-is.

**Pull request merged**
