### PR TITLE
(FACT-1241) Use dmidecode from puppet-agent when available

### PR DESCRIPTION
**Pull request by branan**

### CODE REVIEW

**Comment by branan** [comment]
This retargets #1212 against master

**Comment by branan** [comment]
This requires puppetlabs/puppet-agent#387

**Comment by peterhuene** [comment]
:+1: waiting on dependent PR before merging.

**Comment by branan** [comment]
@peterhuene @haus has +1'd that PR, so if you think it's fine you can probably hit it to get this one in

**Comment by peterhuene** [comment]
Wait on agent CI (currently borked) or merge?

**Comment by joshcooper** [comment]
:+1: to merge now, as per-commit facter#master is green, and only daily job is failing due to pxp-agent on solaris.

**Pull request merged**
